#chiave:streamlit run ./Dictionary.py
import streamlit as st
import random

# Define the dictionaries
English = {
    "brittle": "friabile",
    "tail off":"sfumare, dileguarsi",
    "chatter":"chicchiere",
    "noxious":"nocivo",
    "endowment":"sovvenzione",
    "befoul":"infangare",
    "outline":"contorno, traccia",
    "wicked":"cattiva",
    "shrine":"reliquia",
    "besume":"confondere",
    "up front":"in anticipo",
    "cut back":"tagliare per risparmiare",
    "high-strung":"irrascibile",
    "huff":"ansimare",
    "vent":"sfogare, sfogo",
    "jot":"annotare",
    "con":"raggirare, raggiro",
    "rekindle":"riattivare, rinvigorire",
    "zone out":"sognare ad occhi aperti",
    "hazy":"nebbioso, annebiato",
    "wool":"lana",
    "mushy":"corny, sdolcinato",
    "valiant":"coraggioso",
    "blow through":"sperperare, diffondersi",
    "reinstate":"reintregrare, ripristinare",
    "own up":"confessare",
    "ingrain":"inculcare, instillare",
    "mileage":"chilometraggio",
    "allude":"alludere",
    "let up":"attenuarsi, interrompere, smettere",
    "underlying":"sottostante",
    "disgress":"divagare",
    "harzardous":"pericolos",
    "berate":"rimproverare",
    "moss":"muschio",
    "pluck up":"trovare il coraggio",
    "ripple":"increspatura",
    "sink in":"essere assorbito",
    "deformity":"deformità",
    "write up":"scrivere una critica",
    "stuck-up":"pieno di sè",
    "sound":"saggio",
    "tip off":"informare",
    "repeal":"revocare",
    "see-through":"trasparente",
    "laid-back":"rilassato",
    "unwavering":"deciso",
    "cheesy":"scadente, dozzinale, di cattivo gusto",
    "sliver":"scheggia",
    "oversight":"svista, distrazione",
    "ballot":"voto, votare",
    "jester":"giullare",
    "pun":"gioco di parole",
    "haymaker":"colpo tremendo",
    "cutting-edge":"innovativo",
    "snail":"chiocciola",
    "barge in on":"interrompere",
    "supper":"dinner",
    "rocky":"rocciosos, burrascoso",
    "wither":"appassire",
    "sardonic":"beffardo",
    "let off":" lasciare correre, permettere a di evitare qlc",
    "shuffle":"scompigliare",
    "scold":"berate",
    "wail":"pianto, piangere",
    "deplete":"svuotare, esaurire",
    "pelvis":"bacino",
    "whizz":"sfrecciare",
    "shiver":"rabbrividire, tremolio",
    "prowess":"abilità",
    "outvote":"ricevere più voti",
    "gore":"sangue",
    "precient":"distretto di polizia",
    "commendable":"encomiabile",
    "skim off":"fare la cresta",
    "lumber":"muoversi pesantemente",
    "dank":"umido, moist",
    "bedazzle":"accecare",
    "stakeout":"appostamento, punto di sorveglianza",
    "squish":"spremere, strizzare",
    "forefront":"ribalta, riflettori",
    "dredge up": "rivangare",
    "declutter": "riordinare",
    "heckle":"infastidire",
    "thwart":"sventare",
    "derogatori":"dispregiativo",
    "see-through":"trasparente",
    "roll in":"presentarsi, comparire",
    "pelt":"bombardare, picchiettare",
    "arilock":"intercapedine",
    "ludicrus":"assurdo, ridicolo",
    "titillate":"sollecitare, titillare",
    "scurry":"vuoversi freneticamente",
    "hopscotch":"gioco della campana",
    "overrun":"invadere,eccedere,oltrepassare",
    "deadbolt":"serratura di sicurezza",
    "devoid":"privo",
    "crop up":"show up",
    "come about":"succedere",
    "headstrong":"caparbio",
    "abide":"stick to, stand for",
    "fester":"inasprirsi",
    "toggle":"azionare,far scattare",
    "brandish":"brandire",
    "scrutiny":"esame minuzioso",
    "scuttle":"affondare (proposta),muoversi freneticamente",
    "frown upon":"biasimare, esprimere la propria contrairietà",
    "phase-out":"eliminazione progressiva",
    "phase out":"eliminare progressivamente",
    "bedrock":"base, fondamento",
    "oftentimes":"frequentemente",
    "momentum":"impeto",
    "dovetail":"incastarsi,andare alla perfezione",
    "hitch":"contrattempo",
    "hiccup":"contrattempo",
    "pundit":"critico",
    "plum":"prugna,succoso",
    "reprehensible":"riprovevole",
    "flashpoint":"luogo di crisi;punto di rottura",
    "caterpillar":"bruco",
    "lookout":"punto di osservazione,osservatorio",
    "ad-lib":"improvvisare",
    "dampen":"inumidire,smorzare",
    "prawn":"shrimp",
    "creek":"rusciello",
    "clover":"trifoglio",
    "sublet":"subaffitare",
    "feisty":"esuberante",
    "lapse":"calo di concentrazione, distrazione",
    "fluke":"combinazione, colpo di fortuna",
    "landslide":"frana",
    "swarm":"schiame, sciamare",
    "slum":"bassifondi",
    "click with":"andare d'accordo",
    "backlash":"reazione engativa, contraccolpo"}

French = {"mot":"word",
         "cachottier":"secretive"}

Spanish = {
    "valia": "valore",
    "basura":"spazzatura",
    "arrollar":" drag underneath, knock down, crush",
    "baja":"decrease in price, sick leave",
    "arrollado":"overwhelming",
    "tasa":"fee",
    "relajar":"relax",
    "enfocar":"focus",
    "soler":"Tener costumbre de hacer una cosa",
    "pueblo":"village",
    "huerto":"kitchen garden",
    "plantearse":"consider, think about",
    "a la baja":"on decline",
    "repercusiòn":"consequence",
    "ademàs":"in addition, also",
    "hace rato":"it's been a while",
    "azùcar":"sugar",
    "soler":"usually + verb (it is a verb soler",
    "pan":"bread",
    "grabar":"record, film",
    "decepcionar":"disappoint",
    "hablar acerca":"discuss about",
    "despacio":"slowly, gradually",
    "marcha":"progress, walk",
    "aprovechar":"make most of it, take advantage of",
    "aliviar":"alleviate, relieve, ease",
    "vispera": "vigilia",
    "rebaja":"reduction",
    "recortar":"cut",
    "estimular":"encourage",
    "deprimir":"depress",
    "equivocarse":"get mistaken",
    "restrasar":"postpone, delay",
    "paro":"strike",
    "apuntar":"point at",
    "guardar":"watch over",
    "pendiente":"pending",
    "entorpecer":"hinder",
    "exigir":" require, ask",
    "apetecer":"crave, long for",
    "mantener":"keep",
    "convenio":"agreement",
    "fundamento":"bedrock",
    "arrasar": "stravincere",
    "basura":"garbage",
    "escalòn":"step",
    "techo":"roof",
    "circundante":"circostante",
    "suburbio pobre":"slum",
    "acontecimiento":"event",
    "docena":"dozen",
    "jueves":"thrusday",
    "lujo":"lusso",
    "aparato":"devise",
    "cerca":"vicino",
    "lejos":"far away",
    "culpar":"blame",
    "pitido":"fischio",
    "lanzadera":"shuttle",
    "alertar":"alert, warn",
    "attribuir":"assign, attribute",
    "dar luz":" fare luce",
    "llevar a cado":"carry out",
    "pitar":"fischiare",
    "subvenciòn":"subcidy, grant",
    "caro":"expensive",
    "huelga":"paro",
    "tripulante":"crew member",
    "cese":"stoppage",
    "ablandar":"ammorbidire, rendere più tenero",
    "marisco":"frutti di mare",
    "agotar":"use up, drain, wear out",
    "pesadilla": "nightmare",
    "jubilado":"retired",
    "empresariado":"businessman",
    "direcciòn":"adress",
    "pie":"foot",
    "disparar":"fire, shoot",
    "profundizar":"do something with a deep focus",
    "surgir":" appear, arise",
    "detectar":" detect",
    "tras":"after",
    "descartar":"reject, rule out",
    "degradar":"demote, degrade",
    "escalata":"escalation",
    "echar":"throw",
    "jalar":"pull",
    "estirar":"stretch",
    "cepillo":"toothbrush",
    "advertir":"warn",
    "membresia":"membership",
    "ban(gn)arme":"take a shower",
    "secar":"dry",
    "peinar":"comb",
    "maquillar":"make up",
    "audiphonos":"heapphone",
    "algo asi":"qualcosa del genere",
    "facilitar":"provide,facilitate",
    "apenas":"barely, as soonn as",
    "descansar":"riposarsi",
    "desahogar":"give vent, pat off or free you of debt",
    "recelo":"mistrust",
    "recelar":"suspect, distrust",
    "situar":"collocare  (anche figurativo)",
    "ingreso":"entrata, reddito",
    "informativo":"news",
    "ancho":"width, wide",
    "suen(gn)":"sleep",
    "correo":"mail",
    "alarma":"alarm",
    "librar":"liberarsi, be spared",
    "producirse":"happen",
    "suponer":"suppose, mean",
    "formar":"formare",
    "frente":"fronte, di fronte a",
    "hélice":"elica",
    "aterrizar":"atterrare",
    "acostarme":"lie down, go to bed",
    "alojamiento":"alloggio",
    "cohete":"rocket",
    "mando":"authority, head",
    "entre tanto":" tra i tanti",
    "adoquinado":"pavement",
    "desplazar":"move",
    "repeler":"repel, fend off",
    "alejar":"get away",
    "acà":"here",
    "enfrentar":"confront, face",
    "principio":"inizio",
    "bache":"buca",
    "estrecho":"stretto",
    "alcance":"range",
    "estirada/o":"stuck-up",
    "dañar":"damage, harm",
    "huir":"flee",
    "desplazar":"move",
    "alcanzar":"reach, achieve",
    "incrustar":"conficcare",
    "cuyos":"whose",
    "tras lo cual":"dopo di che",
    "involucrar":"involve",
    "rostro":"face, image",
    "reajuste":"reform, readjustment",
    "asediar":"besiege",
    "destrozar":"destroy",
    "entorno":"enviroment, surrounding",
    "recelo":"mistrust",
    "apartar":"seperate",
    "considerar":"consider, evaluate",
    "debilitar":"weaken",
    "sumamente":"esxtremely",
    "ficha":"card, file"
}

def get_random_word(dictionary):
    if not dictionary:
        raise ValueError("The dictionary is empty")
    return random.choice(list(dictionary.keys()))

# Title of the app
st.title("My Dictionary App")

# Sidebar for dictionary selection
st.sidebar.title("Dictionaries")
dictionary_type = st.sidebar.selectbox("Choose a dictionary", ["English", "Spanish", "French"])

# Sidebar for action selection
st.sidebar.title("Actions")
action = st.sidebar.selectbox(
    "What would you like to do?",
    ["Lookup", "Add New Word", "Random Word"]
)

# Reference the correct dictionary based on selection
selected_dictionary = English if dictionary_type == "English" else French if dictionary_type == "French" else Spanish


# Lookup functionality
if action == "Lookup":
    st.subheader("Lookup a Word")
    word = st.text_input("Enter a word to look up:").strip().lower()
    
    if word:
        definition = selected_dictionary.get(word)
        if definition:
            st.write(f"**{word.capitalize()}:** {definition}")
        else:
            st.write(f"Sorry, the word '{word}' was not found in the dictionary.")

# Add new word functionality
elif action == "Add New Word":
    st.subheader("Add a New Word")
    new_word = st.text_input("Enter the word you want to add:").strip().lower()
    new_definition = st.text_area("Enter the definition for the new word:")
    
    if st.button("Add Word"):
        if new_word in selected_dictionary:
            st.write(f"The word '{new_word}' already exists in the dictionary.")
        else:
            selected_dictionary[new_word] = new_definition
            st.write(f"The word '{new_word}' has been added to the {dictionary_type} dictionary.")

# Random word functionality
elif action == "Random Word":
    st.subheader("Random Word")
    if st.button("Get Random Word"):
        random_word = get_random_word(selected_dictionary)
        st.write(f"**{random_word.capitalize()}:** {selected_dictionary[random_word]}")
