#chiave:streamlit run ./Dictionary.py
import streamlit as st
import random

# Define the dictionaries
English = {
    "brittle": "friabile",
    "tail off":"sfumare, dileguarsi",
    "outreach":"eccedere",
    "sway":"ondeggiare",
    "thoroughfare":"strada principale",
    "reprehend":"rimproverare",
    "workaround":"soluzione temporanea",
    "gamey":"vigoroso",
    "chip away":"scalpellare via",
    "junction":"svincolo",
    "convoy":"scorta, scortare",
    "loot":"bottino",
    "moratorium":"moratoria",
    "tick off":"depennare",
    "chatter":"chicchiere",
    "witty":"astuto",
    "rollover":"rinnovo (finance)",
    "swaddle":"fasciacre",
    "noxious":"nocivo",
    "endowment":"sovvenzione",
    "baffle":"confondere",
    "pummel":"prendere a pugni, distruggere",
    "scrib":"strofinare",
    "befoul":"infangare",
    "outline":"contorno, traccia",
    "wicked":"cattiva",
    "shrine":"reliquia",
    "besume":"confondere",
    "up front":"in anticipo",
    "cut back":"tagliare per risparmiare",
    "high-strung":"irrascibile",
    "huff":"ansimare",
    "vent":"sfogare, sfogo",
    "jot":"annotare",
    "con":"raggirare, raggiro",
    "rekindle":"riattivare, rinvigorire",
    "zone out":"sognare ad occhi aperti",
    "hazy":"nebbioso, annebiato",
    "wool":"lana",
    "mushy":"corny, sdolcinato",
    "valiant":"coraggioso",
    "blow through":"sperperare, diffondersi",
    "reinstate":"reintregrare, ripristinare",
    "own up":"confessare",
    "ingrain":"inculcare, instillare",
    "mileage":"chilometraggio",
    "allude":"alludere",
    "let up":"attenuarsi, interrompere, smettere",
    "underlying":"sottostante",
    "disgress":"divagare",
    "harzardous":"pericolos",
    "berate":"rimproverare",
    "moss":"muschio",
    "pluck up":"trovare il coraggio",
    "ripple":"increspatura",
    "sink in":"essere assorbito",
    "deformity":"deformità",
    "write up":"scrivere una critica",
    "stuck-up":"pieno di sè",
    "sound":"saggio",
    "tip off":"informare",
    "repeal":"revocare",
    "see-through":"trasparente",
    "laid-back":"rilassato",
    "unwavering":"deciso",
    "cheesy":"scadente, dozzinale, di cattivo gusto",
    "sliver":"scheggia",
    "oversight":"svista, distrazione",
    "ballot":"voto, votare",
    "jester":"giullare",
    "pun":"gioco di parole",
    "haymaker":"colpo tremendo",
    "cutting-edge":"innovativo",
    "snail":"chiocciola",
    "barge in on":"interrompere",
    "supper":"dinner",
    "rocky":"rocciosos, burrascoso",
    "wither":"appassire",
    "sardonic":"beffardo",
    "let off":" lasciare correre, permettere a di evitare qlc",
    "shuffle":"scompigliare",
    "scold":"berate",
    "wail":"pianto, piangere",
    "deplete":"svuotare, esaurire",
    "pelvis":"bacino",
    "whizz":"sfrecciare",
    "shiver":"rabbrividire, tremolio",
    "prowess":"abilità",
    "outvote":"ricevere più voti",
    "gore":"sangue",
    "precient":"distretto di polizia",
    "commendable":"encomiabile",
    "skim off":"fare la cresta",
    "lumber":"muoversi pesantemente",
    "dank":"umido, moist",
    "bedazzle":"accecare",
    "stakeout":"appostamento, punto di sorveglianza",
    "squish":"spremere, strizzare",
    "forefront":"ribalta, riflettori",
    "dredge up": "rivangare",
    "declutter": "riordinare",
    "heckle":"infastidire",
    "thwart":"sventare",
    "derogatori":"dispregiativo",
    "see-through":"trasparente",
    "roll in":"presentarsi, comparire",
    "pelt":"bombardare, picchiettare",
    "arilock":"intercapedine",
    "ludicrus":"assurdo, ridicolo",
    "titillate":"sollecitare, titillare",
    "scurry":"vuoversi freneticamente",
    "hopscotch":"gioco della campana",
    "overrun":"invadere,eccedere,oltrepassare",
    "deadbolt":"serratura di sicurezza",
    "devoid":"privo",
    "crop up":"show up",
    "come about":"succedere",
    "headstrong":"caparbio",
    "abide":"stick to, stand for",
    "fester":"inasprirsi",
    "toggle":"azionare,far scattare",
    "brandish":"brandire",
    "scrutiny":"esame minuzioso",
    "scuttle":"affondare (proposta),muoversi freneticamente",
    "frown upon":"biasimare, esprimere la propria contrairietà",
    "phase-out":"eliminazione progressiva",
    "phase out":"eliminare progressivamente",
    "bedrock":"base, fondamento",
    "nagging":"opprimente, assillante",
    "oftentimes":"frequentemente",
    "momentum":"impeto",
    "dovetail":"incastarsi,andare alla perfezione",
    "hitch":"contrattempo",
    "hiccup":"contrattempo",
    "pundit":"critico",
    "spree":"frenesia",
    "defer":"differire, procrastinare",
    "check off":"spuntare",
    "run down":"denigrare",
    "run-down":"cadente, malmesso",
    "plum":"prugna,succoso",
    "reprehensible":"riprovevole",
    "flashpoint":"luogo di crisi;punto di rottura",
    "caterpillar":"bruco",
    "lookout":"punto di osservazione,osservatorio",
    "ad-lib":"improvvisare",
    "dampen":"inumidire,smorzare",
    "prawn":"shrimp",
    "creek":"rusciello",
    "clover":"trifoglio",
    "sublet":"subaffitare",
    "feisty":"esuberante",
    "lapse":"calo di concentrazione, distrazione",
    "fluke":"combinazione, colpo di fortuna",
    "landslide":"frana",
    "swarm":"schiame, sciamare",
    "slum":"bassifondi",
    "click with":"andare d'accordo",
    "backlash":"reazione engativa, contraccolpo"}

French = {"mot":"word",
         "cachottier":"secretive",
         "aujourd'hui":"today",
         "ville":"city"}

Spanish = {
    "valia": "valore",
    "otoño":"autumn",
    "efectivo":"cash",
    "chiso":"cool",
    "hospedaje":"lodging",
    "mover":"move",
    "neta":"truth",
    "fijar":"set",
    "coquetear":"flirt",
    "arriba":"above",
    "boleto":"ticket",
    "llevar a cabo":"carry out",
    "basura":"spazzatura",
    "arrollar":" drag underneath, knock down, crush",
    "baja":"decrease in price, sick leave",
    "arrollado":"overwhelming",
    "dirigir":"run, adress, head",
    "tasa":"fee",
    "sombra":"shadow",
    "sabroso":"tasty",
    "relajar":"relax",
    "inscritir":"carve, engrave",
    "enfocar":"focus",
    "soler":"Tener costumbre de hacer una cosa",
    "pueblo":"village",
    "huerto":"kitchen garden",
    "plantearse":"consider, think about",
    "a la baja":"on decline",
    "imcumplido":"irresponsible, unreliable",
    "repercusiòn":"consequence",
    "ademàs":"in addition, also",
    "hace rato":"it's been a while",
    "azùcar":"sugar",
    "tumbar":"knock down",
    "bloquear":"block, jam",
    "soler":"usually + verb (it is a verb soler",
    "pan":"bread",
    "grabar":"record, film",
    "decepcionar":"disappoint",
    "hablar acerca":"discuss about",
    "despacio":"slowly, gradually",
    "marcha":"progress, walk",
    "aprovechar":"make most of it, take advantage of",
    "aliviar":"alleviate, relieve, ease",
    "vispera": "vigilia",
    "rebaja":"reduction",
    "recortar":"cut",
    "estimular":"encourage",
    "franja":"strip, band",
    "desbordar":"overflow, go beyond",
    "brecha":"hole, rift",
    "cotizar":"be listed",
    "alcade,alcadesa":"mayor",
    "imprevisible":"unpredictable",
    "prolungar":"prolong",
    "meta":"goal, target",
    "comprometerse a":"pledge to",
    "envejecere":"age",
    "deprimir":"depress",
    "equivocarse":"get mistaken",
    "restrasar":"postpone, delay",
    "paro":"strike",
    "apuntar":"point at",
    "guardar":"watch over",
    "pendiente":"pending",
    "agotar":"run out, wear out",
    "entorpecer":"hinder",
    "exigir":" require, ask",
    "acabado":"exhausted",
    "pertenecer":"belong to, be the responsibility",
    "parcela":"plot",
    "medicion":"measuring",
    "a menudo":"often",
    "ajustar":"adjust, stick to",
    "presumir":"brag",
    "apetecer":"crave, long for",
    "mantener":"keep",
    "convenio":"agreement",
    "pila":"battery",
    "inalambrico":"wireless",
    "fundamento":"bedrock",
    "arrasar": "stravincere",
    "basura":"garbage",
    "escalòn":"step",
    "techo":"roof",
    "circundante":"circostante",
    "suburbio pobre":"slum",
    "extensa":"extensive",
    "sabor":"taste",
    "sinfin":"endless",
    "amanecer":"sunset",
    "fogata":"bonfire",
    "acontecimiento":"event",
    "templado":"mild",
    "repartir":"dived up, distribute",
    "fomentar":"promote, fomentar",
    "temprano":"presto",
    "michila":"backpack",
    "priorizar":"prioritize",
    "concurrido":"crowded",
    "concurrir":"meet, get together",
    "agregar":"add",
    "aliado":"ally",
    "erosionar":"erode",
    "abarcar":"cover, span encompass",
    "agarrar":"grab, catch",
    "chamarra":"coat",
    "reto":"challenge",
    "chido":"cool",
    "retar":"sfidare",
    "docena":"dozen",
    "almuerzo":"lunch",
    "jueves":"thrusday",
    "ni siquiera":"not even",
    "pesado":"pesante",
    "lujo":"lusso",
    "tiroteo":"gunfire",
    "intersecciòn":"intersection",
    "rodear":"surround",
    "cabaña":"capanna",
    "contundentemente":"firmly",
    "aparato":"devise",
    "bucear":"nuotare sott'acqua",
    "enlazar":"link",
    "cerca":"vicino",
    "hospedar":"host",
    "mascota":"pet",
    "hospedarse":"lodge, stay",
    "lejos":"far away",
    "cosquillear":"formicolare",
    "gacha":"poltiglia",
    "cosquillas":"solletico",
    "derribar":"demolish",
    "cuadra":"block like street",
    "culpar":"blame",
    "pitido":"fischio",
    "caida":"fall",
    "intendente":"manager",
    "saquear":"loot",
    "interactuar":"interact",
    "poseer":"own, possess",
    "exento":"exempt",
    "seguro":"unsurance",
    "cumplir":"reach, accomplish",
    "fuente":"fountain, source",
    "lanzadera":"shuttle",
    "alertar":"alert, warn",
    "attribuir":"assign, attribute",
    "dar luz":" fare luce",
    "llevar a cado":"carry out",
    "pitar":"fischiare",
    "subvenciòn":"subcidy, grant",
    "caro":"expensive",
    "huelga":"paro",
    "fortaleza":"fortress, stronghold, strenght"
    "tripulante":"crew member",
    "cese":"stoppage",
    "ablandar":"ammorbidire, rendere più tenero",
    "marisco":"frutti di mare",
    "teja":"tile",
    "agotar":"use up, drain, wear out",
    "pesadilla": "nightmare",
    "oscurecer":"get dark",
    "jubilado":"retired",
    "empresariado":"businessman",
    "direcciòn":"adress",
    "lienzo":"canvas",
    "bala":"bullet",
    "mermar":"reduce, descrease",
    "grosero":"rude, gross",
    "antojar":"fancy, having a craving for",
    "pie":"foot",
    "disparar":"fire, shoot",
    "profundizar":"do something with a deep focus",
    "franquicia":"franchise",
    "postre":"dessert",
    "surgir":" appear, arise",
    "detectar":" detect",
    "tras":"after",
    "alcanzar":"reach",
    "descartar":"reject, rule out",
    "degradar":"demote, degrade",
    "escalata":"escalation",
    "echar":"throw",
    "literal":"literal",
    "jalar":"pull",
    "estirar":"stretch",
    "cepillo":"toothbrush",
    "advertir":"warn",
    "membresia":"membership",
    "ban(gn)arme":"take a shower",
    "secar":"dry",
    "peinar":"comb",
    "maquillar":"make up",
    "llevar recorrido":"walk, travel",
    "estomago":"stomach",
    "dosis":"dose",
    "familiarizarse":"get used, get comfortable",
    "coto":"reserve, enclosed land",
    "audiphonos":"heapphone",
    "algo asi":"qualcosa del genere",
    "facilitar":"provide,facilitate",
    "recorrido":"walk, path",
    "mensual":"monthly",
    "ascender":"ascend, climb",
    "apenas":"barely, as soonn as",
    "caber":"be room for, fit",
    "empañar":"stain, fog",
    "propina":"tips",
    "fungir":"serve as, act as",
    "apartarse":" go different ways, get separeted",
    "desahogar":"give vent, pat off or free you of debt",
    "recelo":"mistrust",
    "recelar":"suspect, distrust",
    "situar":"collocare  (anche figurativo)",
    "ingreso":"entrata, reddito",
    "informativo":"news",
    "ancho":"width, wide",
    "suen(gn)":"sleep",
    "correo":"mail",
    "alarma":"alarm",
    "librar":"liberarsi, be spared",
    "producirse":"happen",
    "suponer":"suppose, mean",
    "formar":"formare",
    "frente":"fronte, di fronte a",
    "hélice":"elica",
    "aterrizar":"atterrare",
    "acostarme":"lie down, go to bed",
    "alojamiento":"alloggio",
    "aliar":"combine, bring together",
    "intercambiar":"exchange",
    "aliarse":"form an alliance",
    "disuadir":"dissuade",
    "exacerbar":"exacerbate",
    "tarea":"job, task",
    "desafio":"reto",
    "estrechamente":"closely",
    "suscribir":"subscribe",
    "encubierta":"fraud",
    "arraigar":"root",
    "solicitar":"request, ask for",
    "tener onda":"figo",
    "aislar":"isolate",
    "audifono":"headphone",
    "acostumbrar":"get used to",
    "rehen":"hostage",
    "rama":"branch",
    "cohete":"rocket",
    "mando":"authority, head",
    "actuar":"act, behave",
    "recopilar":"gather",
    "entre tanto":" tra i tanti",
    "adoquinado":"pavement",
    "desplazar":"move",
    "repeler":"repel, fend off",
    "alejar":"get away",
    "acà":"here",
    "enfrentar":"confront, face",
    "principio":"inizio",
    "bache":"buca",
    "estrecho":"stretto",
    "alcance":"range",
    "estirada/o":"stuck-up",
    "dañar":"damage, harm",
    "brigarse":"protect from cold, take shelter",
    "huir":"flee",
    "desplazar":"move",
    "alcanzar":"reach, achieve",
    "incrustar":"conficcare",
    "cuyos":"whose",
    "tras lo cual":"dopo di che",
    "involucrar":"involve",
    "rostro":"face, image",
    "reajuste":"reform, readjustment",
    "asediar":"besiege",
    "destrozar":"destroy",
    "amontonar":"stack, pile",
    "entorno":"enviroment, surrounding",
    "recelo":"mistrust",
    "apartar":"seperate",
    "molestar":"bother",
    "tabla":"table",
    "considerar":"consider, evaluate",
    "debilitar":"weaken",
    "sumamente":"esxtremely",
    "ficha":"card, file"
}

def get_random_word(dictionary):
    if not dictionary:
        raise ValueError("The dictionary is empty")
    return random.choice(list(dictionary.keys()))

# Title of the app
st.title("My Dictionary App")

# Sidebar for dictionary selection
st.sidebar.title("Dictionaries")
dictionary_type = st.sidebar.selectbox("Choose a dictionary", ["English", "Spanish", "French"])

# Sidebar for action selection
st.sidebar.title("Actions")
action = st.sidebar.selectbox(
    "What would you like to do?",
    ["Lookup", "Add New Word", "Random Word"]
)

# Reference the correct dictionary based on selection
selected_dictionary = English if dictionary_type == "English" else French if dictionary_type == "French" else Spanish


# Lookup functionality
if action == "Lookup":
    st.subheader("Lookup a Word")
    word = st.text_input("Enter a word to look up:").strip().lower()
    
    if word:
        definition = selected_dictionary.get(word)
        if definition:
            st.write(f"**{word.capitalize()}:** {definition}")
        else:
            st.write(f"Sorry, the word '{word}' was not found in the dictionary.")

# Add new word functionality
elif action == "Add New Word":
    st.subheader("Add a New Word")
    new_word = st.text_input("Enter the word you want to add:").strip().lower()
    new_definition = st.text_area("Enter the definition for the new word:")
    
    if st.button("Add Word"):
        if new_word in selected_dictionary:
            st.write(f"The word '{new_word}' already exists in the dictionary.")
        else:
            selected_dictionary[new_word] = new_definition
            st.write(f"The word '{new_word}' has been added to the {dictionary_type} dictionary.")

# Random word functionality
elif action == "Random Word":
    st.subheader("Random Word")
    if st.button("Get Random Word"):
        random_word = get_random_word(selected_dictionary)
        st.write(f"**{random_word.capitalize()}:** {selected_dictionary[random_word]}")
